version: 0.2

env:
  variables:
    DOCUUID: "29dc2abb-fc26-403e-bad0-0088c7640168"

phases:
  install:
    commands:
      # Setting up Docker
      - echo "Starting the Docker daemon"
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - export GIT_SOURCE_VERSION=$(git rev-parse HEAD)
      - echo "Building HyperAPI Wheel"
      - python setup.py sdist bdist_wheel
      - aws s3 cp dist/HyperAPI-4.2-py3-none-any.whl s3://pypi.hcube.cool/HyperAPI/HyperAPI-4.2-py3-none-any.whl
      - echo "Installing HyperAPI's environment"
      - pip install dist/HyperAPI-4.2-py3-none-any.whl
      - echo "Generating HyperAPI documentation sources"
      - cd $CODEBUILD_SRC_DIR/docs; chmod +x generate_doc.sh; ./generate_doc.sh $CODEBUILD_SRC_DIR/HyperAPI/hyper_api $DOCUUID
      - python $CODEBUILD_SRC_DIR/scripts/deploy.py -p $CODEBUILD_SRC_DIR/docs/$DOCUUID
      - echo "Building HyperAPI Docker image"
      - cd $CODEBUILD_SRC_DIR/dist
      - docker build -t hypercube/hyperapi . --build-arg hyperapiversion=4.2
      - docker tag hypercube/hyperapi:latest 021798317095.dkr.ecr.eu-central-1.amazonaws.com/hypercube/hyperapi:$GIT_SOURCE_VERSION
      - docker push 021798317095.dkr.ecr.eu-central-1.amazonaws.com/hypercube/hyperapi:$GIT_SOURCE_VERSION
